branches:
  only:
  - master

jobs:
  include:
    - stage: "Build"
      name: "Image api-gateway"
      language: node_js
      node_js:
        - 14
      services:
        - docker
      before_script:
        - cd udagram-api
      script:
        - docker build --build-arg NODE_ENV=production -t udagram-api-gateway .
        - docker tag udagram-api-gateway bfoese/udagram-api-gateway:latest
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push bfoese/udagram-api-gateway

    - language: node_js
      name: "Image api-feed"
      node_js:
        - 14
      services:
        - docker
      before_script:
        - cd udagram-api-feed
      script:
        - docker build --build-arg NODE_ENV=production -t udagram-api-feed .
        - docker tag udagram-api-feed bfoese/udagram-api-feed:latest
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push bfoese/udagram-api-feed

    - language: node_js
      name: "Image api-user"
      node_js:
        - 14
      services:
        - docker
      before_script:
        - cd udagram-api-user
      script:
        - docker build --build-arg NODE_ENV=production -t udagram-api-user .
        - docker tag udagram-api-user bfoese/udagram-api-user:latest
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push bfoese/udagram-api-user

    - language: node_js
      name: "Image frontend"
      node_js:
        - 14
      services:
        - docker
      before_script:
        - cd udagram-frontend
      script:
        - docker build -t udagram-frontend .
        - docker tag udagram-frontend bfoese/udagram-frontend:latest
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push bfoese/udagram-frontend

    # - stage: deploy
    #   name: "Deploy to AWS EKS"
    #   script: ./deploy
